apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service-deployment
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: ticket-service-deployment-label
  template:
    metadata:
      labels:
        app: ticket-service-deployment-label
    spec:
      containers:
        - name: ticket-service
          image: ticket-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080